<!doctype html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <style>
        .selector-for-some-widget {
            box-sizing: content-box;
        }
    </style>
</head>

<body>
    <header>
        <h1> Teste com Slim</h1>
    </header>

    <main class="container">
        <section class="row">
            <div class="col-md-10 col-md-offset-1">
                <article class="row">
                    <section class="col-md-3">
                        <div class="panel panel-info">
                            <div class="panel-heading">Item 1</div>
                            <div class="panel-body">Lorem ipsum dolor sit amet</div>
                        </div>
                    </section>

                    <section class="col-md-3">
                        <div class="panel panel-info">
                            <div class="panel-heading">Item 2</div>
                            <div class="panel-body">Lorem ipsum dolor sit amet</div>
                        </div>
                    </section>

                    <section class="col-md-3">
                        <div class="panel panel-info">
                            <div class="panel-heading">Item 3</div>
                            <div class="panel-body">Lorem ipsum dolor sit amet</div>
                        </div>
                    </section>

                    <section class="col-md-3">
                        <div class="panel panel-info">
                            <div class="panel-heading">Item 4</div>
                            <div class="panel-body">Lorem ipsum dolor sit amet</div>
                        </div>
                    </section>
                </article>

                <article class="row">
                    <div class="col-md-6 col-md-offset-3">

                        {% if flash.hasMessages() %}
                        {{ flash.display() }}
                        {% endif %}

                        <div class="panel panel-default">
                            <div class="panel-body">
                                <form class="form-horizontal" action="/submit" method="POST">

                                    <input type="hidden" name="csrf_name" value="{{ csrf_name }}">
                                    <input type="hidden" name="csrf_value" value="{{ csrf_value }}">

                                    <section class="form-group">
                                        <label class="col-md-3 control-label" for="name">Nome</label>
                                        <div class="col-md-9">
                                            <input type="text" class="form-control" name="name" required>
                                        </div>
                                    </section>

                                    <section class="form-group">
                                        <label class="col-md-3 control-label" for="phone">Telefone</label>
                                        <div class="col-md-9">
                                            <input type="text" class="form-control" name="phone" required>
                                        </div>
                                    </section>

                                    <section class="form-group">
                                        <label class="col-md-3 control-label" for="address">Endereco</label>
                                        <div class="col-md-9">
                                            <input type="text" class="form-control" name="address" required>
                                        </div>
                                    </section>

                                    <section class="form-group">
                                        <label class="col-md-3 control-label" for="description">Descrição</label>
                                        <div class="col-md-9">
                                            <textarea name="description" rows="5" class="form-control" placeholder="Select your item"></textarea>
                                        </div>
                                    </section>

                                    <section class="form-group">
                                        <div class="col-md-9 col-md-offset-3">
                                            <button type="submit" class="btn btn-primary bnt-block">Validar</button>
                                        </div>
                                    </section>
                                </form>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </section>
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>

</html>